stages:
  - deploy


deploy_docker:
  stage: deploy
  image: docker:latest
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME} --build-arg branch=${CI_COMMIT_REF_NAME} .
    - docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_NAME}
  only:
    refs:
      - master
